// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#include "ui.h"


// COMPONENT rightHighBOT

lv_obj_t * ui_rightHighBOT_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rightHighBOT;
    cui_rightHighBOT = lv_imagebutton_create(comp_parent);
    lv_imagebutton_set_src(cui_rightHighBOT, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_heart_png, NULL);
    lv_obj_set_width(cui_rightHighBOT, 64);
    lv_obj_set_height(cui_rightHighBOT, 64);
    lv_obj_set_x(cui_rightHighBOT, 102);
    lv_obj_set_y(cui_rightHighBOT, -75);
    lv_obj_set_align(cui_rightHighBOT, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_RIGHTHIGHBOT_NUM);
    children[UI_COMP_RIGHTHIGHBOT_RIGHTHIGHBOT] = cui_rightHighBOT;
    lv_obj_add_event_cb(cui_rightHighBOT, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rightHighBOT, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_rightHighBOT_create_hook(cui_rightHighBOT);
    return cui_rightHighBOT;
}

