// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#ifndef _UI_COMP_LEFTLOW_H
#define _UI_COMP_LEFTLOW_H

#include "ui_components.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT leftLow
#define UI_COMP_LEFTLOW_LEFTLOW 0
#define _UI_COMP_LEFTLOW_NUM 1
lv_obj_t * ui_leftLow_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
