// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#include "ui_components.h"

void ui_control_screen_init(void)
{
    ui_control = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_control, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_control);
    lv_image_set_src(ui_Image11, &ui_img_1086554574);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 174
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ControlLeftUp = lv_imagebutton_create(ui_control);
    lv_imagebutton_set_src(ui_ControlLeftUp, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_width(ui_ControlLeftUp, 64);
    lv_obj_set_height(ui_ControlLeftUp, 53);
    lv_obj_set_x(ui_ControlLeftUp, -102);
    lv_obj_set_y(ui_ControlLeftUp, -75);
    lv_obj_set_align(ui_ControlLeftUp, LV_ALIGN_CENTER);

    ui_ControlLeftDown = lv_imagebutton_create(ui_control);
    lv_imagebutton_set_src(ui_ControlLeftDown, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_fan_png, NULL);
    lv_obj_set_width(ui_ControlLeftDown, 64);
    lv_obj_set_height(ui_ControlLeftDown, 57);
    lv_obj_set_x(ui_ControlLeftDown, -101);
    lv_obj_set_y(ui_ControlLeftDown, 45);
    lv_obj_set_align(ui_ControlLeftDown, LV_ALIGN_CENTER);

    ui_ControlRightUp = lv_imagebutton_create(ui_control);
    lv_imagebutton_set_src(ui_ControlRightUp, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_smog_png, NULL);
    lv_obj_set_width(ui_ControlRightUp, 64);
    lv_obj_set_height(ui_ControlRightUp, 54);
    lv_obj_set_x(ui_ControlRightUp, 102);
    lv_obj_set_y(ui_ControlRightUp, -75);
    lv_obj_set_align(ui_ControlRightUp, LV_ALIGN_CENTER);

    ui_ControlRightDown = lv_imagebutton_create(ui_control);
    lv_imagebutton_set_src(ui_ControlRightDown, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bulb_png, NULL);
    lv_obj_set_width(ui_ControlRightDown, 64);
    lv_obj_set_height(ui_ControlRightDown, 56);
    lv_obj_set_x(ui_ControlRightDown, 101);
    lv_obj_set_y(ui_ControlRightDown, 45);
    lv_obj_set_align(ui_ControlRightDown, LV_ALIGN_CENTER);

    ui_Humidifier = lv_label_create(ui_control);
    lv_obj_set_width(ui_Humidifier, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidifier, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidifier, 101);
    lv_obj_set_y(ui_Humidifier, -30);
    lv_obj_set_align(ui_Humidifier, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidifier, "humidifier");

    ui_fan = lv_label_create(ui_control);
    lv_obj_set_width(ui_fan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan, -101);
    lv_obj_set_y(ui_fan, 90);
    lv_obj_set_align(ui_fan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fan, "fan");

    ui_led = lv_label_create(ui_control);
    lv_obj_set_width(ui_led, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_led, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_led, 101);
    lv_obj_set_y(ui_led, 90);
    lv_obj_set_align(ui_led, LV_ALIGN_CENTER);
    lv_label_set_text(ui_led, "led");

    ui_ControlBack = lv_label_create(ui_control);
    lv_obj_set_width(ui_ControlBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ControlBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ControlBack, -101);
    lv_obj_set_y(ui_ControlBack, -30);
    lv_obj_set_align(ui_ControlBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ControlBack, "back");

    lv_obj_add_event_cb(ui_ControlLeftUp, ui_event_ControlLeftUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ControlLeftDown, ui_event_ControlLeftDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ControlRightUp, ui_event_ControlRightUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ControlRightDown, ui_event_ControlRightDown, LV_EVENT_ALL, NULL);

}
