// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#include "ui_components.h"

void ui_comp_bluetooth_create_hook(lv_obj_t * comp)
{
}

void ui_comp_leftLow_create_hook(lv_obj_t * comp)
{
}

void ui_comp_rightHighBOT_create_hook(lv_obj_t * comp)
{
}
