// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#include "ui_components.h"

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backgroundImg = lv_image_create(ui_home);
    lv_image_set_src(ui_backgroundImg, &ui_img_1086554574);
    lv_obj_set_width(ui_backgroundImg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_backgroundImg, LV_SIZE_CONTENT);    /// 174
    lv_obj_set_align(ui_backgroundImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgroundImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backgroundImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightHighBOT1 = lv_imagebutton_create(ui_home);
    lv_imagebutton_set_src(ui_rightHighBOT1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_heart_png, NULL);
    lv_obj_set_width(ui_rightHighBOT1, 64);
    lv_obj_set_height(ui_rightHighBOT1, 64);
    lv_obj_set_x(ui_rightHighBOT1, 102);
    lv_obj_set_y(ui_rightHighBOT1, -75);
    lv_obj_set_align(ui_rightHighBOT1, LV_ALIGN_CENTER);

    ui_leftHighBOT = lv_imagebutton_create(ui_home);
    lv_imagebutton_set_src(ui_leftHighBOT, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_control_png, NULL);
    lv_obj_set_width(ui_leftHighBOT, 64);
    lv_obj_set_height(ui_leftHighBOT, 53);
    lv_obj_set_x(ui_leftHighBOT, -102);
    lv_obj_set_y(ui_leftHighBOT, -75);
    lv_obj_set_align(ui_leftHighBOT, LV_ALIGN_CENTER);

    ui_bluetooth1 = lv_imagebutton_create(ui_home);
    lv_imagebutton_set_src(ui_bluetooth1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bluetooth2_png, NULL);
    lv_obj_set_width(ui_bluetooth1, 64);
    lv_obj_set_height(ui_bluetooth1, 57);
    lv_obj_set_x(ui_bluetooth1, -101);
    lv_obj_set_y(ui_bluetooth1, 45);
    lv_obj_set_align(ui_bluetooth1, LV_ALIGN_CENTER);

    ui_leftHigh = lv_label_create(ui_home);
    lv_obj_set_width(ui_leftHigh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leftHigh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_leftHigh, -101);
    lv_obj_set_y(ui_leftHigh, -30);
    lv_obj_set_align(ui_leftHigh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_leftHigh, "control");

    ui_rightHigh = lv_label_create(ui_home);
    lv_obj_set_width(ui_rightHigh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rightHigh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rightHigh, 101);
    lv_obj_set_y(ui_rightHigh, -30);
    lv_obj_set_align(ui_rightHigh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rightHigh, "heartbeat");

    ui_leftLow = lv_label_create(ui_home);
    lv_obj_set_width(ui_leftLow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leftLow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_leftLow, -101);
    lv_obj_set_y(ui_leftLow, 90);
    lv_obj_set_align(ui_leftLow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_leftLow, "bluetooth");

    ui_Temp = lv_label_create(ui_home);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, 42);
    lv_obj_set_y(ui_Temp, 57);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp, "Temp");

    ui_Hum = lv_label_create(ui_home);
    lv_obj_set_width(ui_Hum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hum, 43);
    lv_obj_set_y(ui_Hum, 83);
    lv_obj_set_align(ui_Hum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hum, "Hum");

    ui_tempBar = lv_bar_create(ui_home);
    lv_bar_set_value(ui_tempBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_tempBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_tempBar, 40);
    lv_obj_set_height(ui_tempBar, 10);
    lv_obj_set_x(ui_tempBar, 125);
    lv_obj_set_y(ui_tempBar, 58);
    lv_obj_set_align(ui_tempBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_tempBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_tempBar,
                                                                                              lv_obj_get_style_pad_right(ui_tempBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_humBar = lv_bar_create(ui_home);
    lv_bar_set_value(ui_humBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_humBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_humBar, 40);
    lv_obj_set_height(ui_humBar, 10);
    lv_obj_set_x(ui_humBar, 125);
    lv_obj_set_y(ui_humBar, 82);
    lv_obj_set_align(ui_humBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_humBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_humBar,
                                                                                             lv_obj_get_style_pad_right(ui_humBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_tempset = lv_label_create(ui_home);
    lv_obj_set_width(ui_tempset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempset, 92);
    lv_obj_set_y(ui_tempset, 58);
    lv_obj_set_align(ui_tempset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempset, "°C");

    ui_humset = lv_label_create(ui_home);
    lv_obj_set_width(ui_humset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humset, 94);
    lv_obj_set_y(ui_humset, 83);
    lv_obj_set_align(ui_humset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humset, "%");

    ui_humData = lv_label_create(ui_home);
    lv_obj_set_width(ui_humData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humData, 74);
    lv_obj_set_y(ui_humData, 83);
    lv_obj_set_align(ui_humData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humData, "--");

    ui_tempData = lv_label_create(ui_home);
    lv_obj_set_width(ui_tempData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempData, 74);
    lv_obj_set_y(ui_tempData, 58);
    lv_obj_set_align(ui_tempData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempData, "--");

    lv_obj_add_event_cb(ui_rightHighBOT1, ui_event_rightHighBOT1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftHighBOT, ui_event_leftHighBOT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bluetooth1, ui_event_bluetooth1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_home, ui_event_home, LV_EVENT_ALL, NULL);

}
