// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#include "ui_components.h"

void ui_bluetooth_screen_init(void)
{
    ui_bluetooth = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_bluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_bluetooth);
    lv_image_set_src(ui_Image1, &ui_img_1086554574);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 174
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_bluetooth);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -316);
    lv_obj_set_y(ui_Label1, 180);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "back");

    ui_blueLeftup = lv_imagebutton_create(ui_bluetooth);
    lv_imagebutton_set_src(ui_blueLeftup, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_width(ui_blueLeftup, 64);
    lv_obj_set_height(ui_blueLeftup, 53);
    lv_obj_set_x(ui_blueLeftup, -102);
    lv_obj_set_y(ui_blueLeftup, -75);
    lv_obj_set_align(ui_blueLeftup, LV_ALIGN_CENTER);

    ui_bluetoothLabel = lv_label_create(ui_bluetooth);
    lv_obj_set_width(ui_bluetoothLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluetoothLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluetoothLabel, 0);
    lv_obj_set_y(ui_bluetoothLabel, 90);
    lv_obj_set_align(ui_bluetoothLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bluetoothLabel, "connecting...");

    ui_bluetoothBack = lv_label_create(ui_bluetooth);
    lv_obj_set_width(ui_bluetoothBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluetoothBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluetoothBack, -101);
    lv_obj_set_y(ui_bluetoothBack, -30);
    lv_obj_set_align(ui_bluetoothBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bluetoothBack, "back");

    lv_obj_add_event_cb(ui_blueLeftup, ui_event_blueLeftup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bluetooth, ui_event_bluetooth, LV_EVENT_ALL, NULL);

}
