// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#ifndef _SQUARELINE_PROJECT_CHANGE_UI_H
#define _SQUARELINE_PROJECT_CHANGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_backgroundImg;
void ui_event_rightHighBOT1(lv_event_t * e);
extern lv_obj_t * ui_rightHighBOT1;
void ui_event_leftHighBOT(lv_event_t * e);
extern lv_obj_t * ui_leftHighBOT;
void ui_event_bluetooth1(lv_event_t * e);
extern lv_obj_t * ui_bluetooth1;
extern lv_obj_t * ui_leftHigh;
extern lv_obj_t * ui_rightHigh;
extern lv_obj_t * ui_leftLow;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_Hum;
extern lv_obj_t * ui_tempBar;
extern lv_obj_t * ui_humBar;
extern lv_obj_t * ui_tempset;
extern lv_obj_t * ui_humset;
extern lv_obj_t * ui_humData;
extern lv_obj_t * ui_tempData;
// CUSTOM VARIABLES

// SCREEN: ui_control
void ui_control_screen_init(void);
extern lv_obj_t * ui_control;
extern lv_obj_t * ui_Image11;
void ui_event_ControlLeftUp(lv_event_t * e);
extern lv_obj_t * ui_ControlLeftUp;
void ui_event_ControlLeftDown(lv_event_t * e);
extern lv_obj_t * ui_ControlLeftDown;
void ui_event_ControlRightUp(lv_event_t * e);
extern lv_obj_t * ui_ControlRightUp;
void ui_event_ControlRightDown(lv_event_t * e);
extern lv_obj_t * ui_ControlRightDown;
extern lv_obj_t * ui_Humidifier;
extern lv_obj_t * ui_fan;
extern lv_obj_t * ui_led;
extern lv_obj_t * ui_ControlBack;
// CUSTOM VARIABLES

// SCREEN: ui_heartmeasuring
void ui_heartmeasuring_screen_init(void);
void ui_event_heartmeasuring(lv_event_t * e);
extern lv_obj_t * ui_heartmeasuring;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label16;
void ui_event_HeartLeftUp(lv_event_t * e);
extern lv_obj_t * ui_HeartLeftUp;
extern lv_obj_t * ui_Measuring;
extern lv_obj_t * ui_HeartResult;
extern lv_obj_t * ui_HeartBack;
// CUSTOM VARIABLES

// SCREEN: ui_bluetooth
void ui_bluetooth_screen_init(void);
void ui_event_bluetooth(lv_event_t * e);
extern lv_obj_t * ui_bluetooth;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
void ui_event_blueLeftup(lv_event_t * e);
extern lv_obj_t * ui_blueLeftup;
extern lv_obj_t * ui_bluetoothLabel;
extern lv_obj_t * ui_bluetoothBack;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1086554574);    // assets/배경사진.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_control_png);    // assets/control.png
LV_IMG_DECLARE(ui_img_bluetooth2_png);    // assets/bluetooth2.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets/fan.png
LV_IMG_DECLARE(ui_img_smog_png);    // assets/smog.png
LV_IMG_DECLARE(ui_img_bulb_png);    // assets/bulb.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
