// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#ifndef _UI_COMP_RIGHTHIGHBOT_H
#define _UI_COMP_RIGHTHIGHBOT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rightHighBOT
#define UI_COMP_RIGHTHIGHBOT_RIGHTHIGHBOT 0
#define _UI_COMP_RIGHTHIGHBOT_NUM 1
lv_obj_t * ui_rightHighBOT_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
