// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project_change

#ifndef _UI_COMP_BLUETOOTH_H
#define _UI_COMP_BLUETOOTH_H

#include "ui_components.h"
#ifdef __cplusplus
extern "C" {
#endif

// 컴포넌트 정의
#define UI_COMP_BLUETOOTH_BLUETOOTH 0
#define _UI_COMP_BLUETOOTH_NUM 1

// 함수 선언
lv_obj_t * ui_bluetooth_create(lv_obj_t * comp_parent);
void ui_event_comp_bluetooth_bluetooth(lv_event_t * e);
void ui_comp_bluetooth_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
}
#endif

#endif // _UI_COMP_BLUETOOTH_H

